"""Synthetic company for the demo (mode A). Fictional: no real people or data.

Ravi is leaving. Priya (mid) already works near his code; Sam (junior) is new.
The undocumented decisions around billing retries, the ledger sync and month-end
reconciliation exist only in Ravi's head, which is what the interview captures.
"""
from knowledge_transfer.schemas import SourceBundle

BUNDLE = SourceBundle.model_validate({
    "people": [
        {"id": "ravi", "name": "Ravi Menon", "role": "Senior Backend Engineer",
         "seniority": "senior", "status": "leaving"},
        {"id": "priya", "name": "Priya Nair", "role": "Backend Engineer", "seniority": "mid"},
        {"id": "sam", "name": "Sam Carter", "role": "Junior Backend Engineer", "seniority": "junior"},
        {"id": "meera", "name": "Meera Iyer", "role": "Platform Engineer", "seniority": "senior"},
    ],
    "items": [
        {"id": "payments-domain-basics", "name": "Payments domain basics", "kind": "topic",
         "description": "Authorisation, capture, settlement and refunds as Northwind uses them."},
        {"id": "data-model-basics", "name": "Core data model", "kind": "topic",
         "description": "Accounts, invoices, payments and ledger entries."},
        {"id": "billing-service", "name": "Billing service", "kind": "system",
         "description": "Creates invoices and charges customers."},
        {"id": "invoice-generator", "name": "Invoice generator", "kind": "system",
         "description": "Renders invoice PDFs for the billing service."},
        {"id": "payment-gateway-adapter", "name": "Payment gateway adapter", "kind": "system",
         "description": "Wraps the external payment gateway API."},
        {"id": "gateway-sandbox-quirks", "name": "Gateway sandbox quirks", "kind": "topic",
         "description": "Where the gateway sandbox behaves differently from production."},
        {"id": "billing-retry-scheduler", "name": "Billing retry scheduler", "kind": "system",
         "description": "Retries failed charges on a schedule."},
        {"id": "retry-wait-40-minutes", "name": "Why retries wait 40 minutes", "kind": "decision",
         "description": "The delay between the first and second charge retry."},
        {"id": "idempotency-key-scheme", "name": "Idempotency key scheme", "kind": "decision",
         "description": "How charge requests are made safe to repeat."},
        {"id": "webhook-dispatcher", "name": "Webhook dispatcher", "kind": "system",
         "description": "Sends payment events to customer endpoints."},
        {"id": "ledger-sync-job", "name": "Ledger sync job", "kind": "system",
         "description": "Copies payments into the accounting ledger every night."},
        {"id": "ledger-sync-at-0200", "name": "Why the ledger sync runs at 02:00", "kind": "decision",
         "description": "The schedule of the nightly ledger sync."},
        {"id": "reconciliation-batch", "name": "Reconciliation batch", "kind": "system",
         "description": "Matches gateway payouts against ledger entries."},
        {"id": "month-end-close", "name": "Month-end close procedure", "kind": "topic",
         "description": "The manual steps finance relies on at month end."},
        {"id": "feature-flag-service", "name": "Feature flag service", "kind": "system",
         "description": "Runtime switches for risky behaviour."},
        {"id": "on-call-runbook", "name": "On-call runbook", "kind": "topic",
         "description": "First response for payment incidents."},
    ],
    "documents": [
        {"id": "doc-billing-design", "title": "Billing service design doc",
         "covers": ["billing-service"]},
        {"id": "doc-gateway-readme", "title": "Gateway adapter README",
         "covers": ["payment-gateway-adapter"]},
        {"id": "doc-runbook", "title": "Payments on-call runbook", "covers": ["on-call-runbook"]},
        {"id": "doc-flags", "title": "Feature flags guide", "covers": ["feature-flag-service"]},
        {"id": "doc-primer", "title": "Payments primer",
         "covers": ["payments-domain-basics", "data-model-basics"]},
        {"id": "doc-invoice", "title": "Invoice generator notes", "covers": ["invoice-generator"]},
    ],
    "contributions": [
        {"person": "ravi", "item": "billing-service", "rel": "WORKED_ON", "source": "ticket", "ref": "BILL-101"},
        {"person": "ravi", "item": "invoice-generator", "rel": "WORKED_ON", "source": "ticket", "ref": "BILL-140"},
        {"person": "ravi", "item": "billing-retry-scheduler", "rel": "OWNS", "source": "code", "ref": "retry/scheduler.py"},
        {"person": "ravi", "item": "retry-wait-40-minutes", "rel": "AUTHORED", "source": "ticket", "ref": "BILL-212"},
        {"person": "ravi", "item": "idempotency-key-scheme", "rel": "AUTHORED", "source": "ticket", "ref": "BILL-087"},
        {"person": "ravi", "item": "gateway-sandbox-quirks", "rel": "WORKED_ON", "source": "ticket", "ref": "PAY-319"},
        {"person": "ravi", "item": "ledger-sync-job", "rel": "OWNS", "source": "code", "ref": "ledger/sync.py"},
        {"person": "ravi", "item": "ledger-sync-at-0200", "rel": "AUTHORED", "source": "ticket", "ref": "FIN-054"},
        {"person": "ravi", "item": "reconciliation-batch", "rel": "OWNS", "source": "code", "ref": "recon/batch.py"},
        {"person": "ravi", "item": "month-end-close", "rel": "WORKED_ON", "source": "ticket", "ref": "FIN-071"},
        {"person": "ravi", "item": "payment-gateway-adapter", "rel": "WORKED_ON", "source": "ticket", "ref": "PAY-120"},
        {"person": "ravi", "item": "on-call-runbook", "rel": "WORKED_ON", "source": "doc", "ref": "doc-runbook"},
        {"person": "priya", "item": "billing-service", "rel": "WORKED_ON", "source": "ticket", "ref": "BILL-188"},
        {"person": "priya", "item": "webhook-dispatcher", "rel": "OWNS", "source": "code", "ref": "webhooks/"},
        {"person": "priya", "item": "payment-gateway-adapter", "rel": "WORKED_ON", "source": "ticket", "ref": "PAY-201"},
        {"person": "meera", "item": "payment-gateway-adapter", "rel": "OWNS", "source": "code", "ref": "gateway/"},
        {"person": "meera", "item": "feature-flag-service", "rel": "OWNS", "source": "code", "ref": "flags/"},
        {"person": "meera", "item": "on-call-runbook", "rel": "WORKED_ON", "source": "doc", "ref": "doc-runbook"},
    ],
    "links": [
        {"src": "billing-service", "rel": "DEPENDS_ON", "dst": "payment-gateway-adapter"},
        {"src": "billing-service", "rel": "DEPENDS_ON", "dst": "invoice-generator"},
        {"src": "billing-retry-scheduler", "rel": "DEPENDS_ON", "dst": "billing-service"},
        {"src": "billing-retry-scheduler", "rel": "DEPENDS_ON", "dst": "payment-gateway-adapter"},
        {"src": "billing-retry-scheduler", "rel": "DEPENDS_ON", "dst": "idempotency-key-scheme"},
        {"src": "webhook-dispatcher", "rel": "DEPENDS_ON", "dst": "billing-retry-scheduler"},
        {"src": "ledger-sync-job", "rel": "DEPENDS_ON", "dst": "billing-service"},
        {"src": "reconciliation-batch", "rel": "DEPENDS_ON", "dst": "ledger-sync-job"},
        {"src": "reconciliation-batch", "rel": "DEPENDS_ON", "dst": "payment-gateway-adapter"},
        {"src": "month-end-close", "rel": "DEPENDS_ON", "dst": "reconciliation-batch"},
        {"src": "payments-domain-basics", "rel": "PREREQUISITE_OF", "dst": "billing-service"},
        {"src": "data-model-basics", "rel": "PREREQUISITE_OF", "dst": "billing-service"},
        {"src": "payment-gateway-adapter", "rel": "PREREQUISITE_OF", "dst": "billing-retry-scheduler"},
        {"src": "gateway-sandbox-quirks", "rel": "PREREQUISITE_OF", "dst": "payment-gateway-adapter"},
        {"src": "billing-service", "rel": "PREREQUISITE_OF", "dst": "billing-retry-scheduler"},
        {"src": "idempotency-key-scheme", "rel": "PREREQUISITE_OF", "dst": "billing-retry-scheduler"},
        {"src": "billing-retry-scheduler", "rel": "PREREQUISITE_OF", "dst": "retry-wait-40-minutes"},
        {"src": "billing-service", "rel": "PREREQUISITE_OF", "dst": "ledger-sync-job"},
        {"src": "ledger-sync-job", "rel": "PREREQUISITE_OF", "dst": "ledger-sync-at-0200"},
        {"src": "ledger-sync-job", "rel": "PREREQUISITE_OF", "dst": "reconciliation-batch"},
        {"src": "reconciliation-batch", "rel": "PREREQUISITE_OF", "dst": "month-end-close"},
    ],
    "knows": [
        {"person": "priya", "item": "payments-domain-basics", "level": 3},
        {"person": "priya", "item": "data-model-basics", "level": 3},
        {"person": "priya", "item": "billing-service", "level": 3},
        {"person": "priya", "item": "payment-gateway-adapter", "level": 2},
        {"person": "priya", "item": "webhook-dispatcher", "level": 3},
        {"person": "priya", "item": "invoice-generator", "level": 2},
        {"person": "priya", "item": "on-call-runbook", "level": 2},
        {"person": "sam", "item": "data-model-basics", "level": 2},
        {"person": "sam", "item": "payments-domain-basics", "level": 1},
    ],
})
