"""create interviews and handover plans

Revision ID: 723622ca196c
Revises: 
Create Date: 2026-10-09 15:29:58.917768

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '723622ca196c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handover_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('leaver', sa.String(length=255), nullable=False),
    sa.Column('receiver', sa.String(length=255), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handover_plans'))
    )
    op.create_index(op.f('ix_handover_plans_leaver'), 'handover_plans', ['leaver'], unique=False)
    op.create_index(op.f('ix_handover_plans_receiver'), 'handover_plans', ['receiver'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('leaver', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews'))
    )
    op.create_index(op.f('ix_interviews_leaver'), 'interviews', ['leaver'], unique=False)
    op.create_table('interview_turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answer_type', sa.String(length=32), nullable=True),
    sa.Column('is_follow_up', sa.Boolean(), nullable=False),
    sa.Column('new_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_interview_turns_interview_id_interviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_turns')),
    sa.UniqueConstraint('interview_id', 'seq', name=op.f('uq_interview_turns_interview_id_seq'))
    )
    op.create_index(op.f('ix_interview_turns_interview_id'), 'interview_turns', ['interview_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_turns_interview_id'), table_name='interview_turns')
    op.drop_table('interview_turns')
    op.drop_index(op.f('ix_interviews_leaver'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_handover_plans_receiver'), table_name='handover_plans')
    op.drop_index(op.f('ix_handover_plans_leaver'), table_name='handover_plans')
    op.drop_table('handover_plans')
    # ### end Alembic commands ###
